version: '3'
services:
  video-gallery-v4-db:
    container_name: video-gallery-v4
    platform: linux/arm64
    image: timescale/timescaledb:latest-pg15
    restart: always
    ports:
      - '${DB_PORT}:5440'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: '${DB_NAME}'
    volumes:
      - video-gallery-v4-db-volume:/var/lib/postgresql/data

volumes:
  video-gallery-v4-db-volume:
